### ISSUE TITLE
Inconsistent parameter documentation

### ISSUE THREAD

**Issue by bluepuma77** [ether/etherpad-lite-jquery-plugin#18]
Plugin options and parameter are a bit unclear to me.

The example puts true/false in quotation marks:
```
$('#examplePadBasic').pad({'padId':'test','showChat':'true'});
```
But the overview leaves out the quotation marks:
```
'showChat'         : false, // If you want to show the chat button or not
```
Which way is correct?

**Comment by JohnMcLear** [comment]
bool is correct

https://github.com/ether/etherpad-lite-jquery-plugin/blob/master/js/etherpad.js#L8

I will update the example
