### ISSUE TITLE
Is there any way of getting the "readOnlyPadId" from an embedded pad in your site

### ISSUE THREAD

**Issue by cdparra** [ether/etherpad-lite-jquery-plugin#21]
How can I access the readOnlyPadId from the client when I am embedding a pad? 

I am developing an web app that will use Etherpad to provide collaborative editing capabilities for a close group of activists and part of the app is to store the readOnlyPadId so that if a another user that is not part of group loads the app, he/she will only see the content and not the editor.

**Comment by lpagliari** [comment]
I guess you'll have to know the APIKEY and call [getReadOnlyID](http://etherpad.org/doc/v1.6.0/#index_getreadonlyid_padid). Ex: `http://my.domain.com/api/1/getReadOnlyID?apikey=secret&padID=mypadid`
